#!/bin/sh
#
# Author: Denis de Bernardy <http://www.mesoconcepts.com>
# Version: 0.1
# BSD licensed
#

if [ ! -f wp-config.php ]; then
	echo 'Invalid WP install'
	exit 1
fi

if [ "$1" == '' ]; then
	echo 'Invalid diff file name'
	exit 1
fi

ticket=~/Desktop/$1.diff

svn diff > $ticket