#!/bin/sh
#
# Author: Denis de Bernardy <http://www.mesoconcepts.com>
# Version: 0.1
# BSD licensed
#

rm *.diff 2> /dev/null
rm *.patch 2> /dev/null
rm *.rej 2> /dev/null
rm *.orig 2> /dev/null
find . -name *.diff -exec rm '{}' \;
find . -name *.patch -exec rm '{}' \;
find . -name *.rej -exec rm '{}' \;
find . -name *.orig -exec rm '{}' \;
svn revert -R * -q
